[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pytest-fixturize"
description = "This plugin is intended to provide arbitrary attributes as `pytest` fixtures."
version = "0.1.0"
readme = "README.rst"
requires-python = ">=3.10"
authors = [{ name = "Nikita Antonenkov", email = "krigar1184@gmail.com" }]
maintainers = [{ name = "Nikita Antonenkov", email = "krigar1184@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
  "Framework :: Pytest",
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Testing",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
  "License :: OSI Approved :: MIT License",
]
dependencies = ["pytest>=6.2.0"]
[project.urls]
Repository = "https://github.com/krigar1184/pytest-fixturize"
[project.entry-points.pytest11]
fixturize = "pytest_fixturize.plugin"

[dependency-groups]
dev = [
    "tox (>=4.60.0,<5.0.0)"
]
